[package]
name = "snow_frontend_egui"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.23", features = ["derive"] }
crossbeam-channel = "0.5.14"
eframe = "0.30.0"
egui-file-dialog = "0.8.0"
env_logger = "0.11.6"
log = "0.4.22"
snow_core = { version = "0.1.0", path = "../core", features = ["mmap"] }

[lints]
workspace = true
