[package]
name = "snow_core"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
anyhow = { version = "1.0.86", features = ["backtrace"] }
arrayvec = { version = "0.7.4", features = ["serde"] }
chrono = "0.4.38"
crossbeam = "0.8.4"
crossbeam-channel = "0.5.13"
either = "1.13.0"
flate2 = "1.0.30"
itertools = "0.13.0"
log = { version = "0.4.22", features = ["std"] }
num = "0.4.3"
num-derive = "0.4.2"
num-traits = "0.2.19"
proc-bitfield = "0.4.0"
serde = { version = "1.0.203", features = ["serde_derive", "derive"] }
serde_json = "1.0.117"
strum = { version = "0.26.3", features = ["derive"] }
thiserror = "1.0.61"
