[package]
name = "snow_floppy"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
binrw = "0.14.0"
crc = "3.2.1"
log = "0.4.22"
strum = { version = "0.26.3", features = ["derive"] }

[lints]
workspace = true
