name: Build - Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-2022
    defaults:
      run:
        shell: msys2 {0}

    strategy:
      matrix:
        environment:
          - msystem: MINGW64
            prefix: mingw-w64-x86_64

    steps:
    - uses: actions/checkout@v4
    - name: Prepare MSYS2 environment
      uses: msys2/setup-msys2@v2
      id: msys2
      with:
        release: false
        update: true
        msystem: ${{ matrix.environment.msystem }}
        pacboy: >-
          rust:p
          SDL2:p
          pkg-config:p
    - name: Build release
      run: cargo build --verbose --release
    - name: Create packaging directory
      run: mkdir snow
    - name: Gather files
      run: cp 'target/release/snow_frontend_tui.exe' '${{ steps.msys2.outputs.msys2-location }}/mingw64/bin/SDL2.dll' snow/
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: 'snow-windows-x64-gha${{ github.run_number }}'
        if-no-files-found: error
        path: snow/*
