name: Build and test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Update package repos
      run: sudo apt-get -y update
    - name: Install prerequisites
      run: sudo apt-get -y install libsdl2-dev python3
    - name: Install cargo-llvm-cov
      uses: taiki-e/install-action@cargo-llvm-cov
    - name: Fetch submodules
      run: git submodule update --init --recursive
    - name: Generate test data
      working-directory: ./testdata/m68000
      run: python3 decode.py
    - name: Code formatting check
      run: cargo fmt --check
    - name: Clippy lint
      run: cargo clippy --all -- -D warnings
    - name: Build
      run: cargo build --verbose
    - name: Build release
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose

