name: Checks and tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Update package repos
      run: sudo apt-get -y update
    - name: Install prerequisites
      run: sudo apt-get -y install libsdl2-dev
    - name: Install cargo-llvm-cov
      uses: taiki-e/install-action@cargo-llvm-cov
    - name: Fetch submodules
      run: git submodule update --init --recursive
    - name: Code formatting check
      run: cargo fmt --check
    - name: Clippy lint
      run: cargo clippy --all -- -D warnings
    - name: Generate test data
      working-directory: ./testdata/m68000
      run: python3 decode.py
    - name: Generate code coverage
      run: cargo llvm-cov --workspace --codecov --output-path codecov.json
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: codecov.json
        fail_ci_if_error: true

